### ISSUE TITLE
Startup: base url null -> Null check operator exception

### ISSUE THREAD

**Issue by ToniHeiss** [sibvisions/flutter_jvx#187]
I sometimes get the following error when exiting an app after having already lost the connection:

```

I/flutter ( 5208): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 5208): │ Null check operator used on a null value
I/flutter ( 5208): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 5208): │ #0   StartupCommandProcessor.processCommand (package:flutter_jvx/src/service/command/shared/processor/api/start_up_command_processor.dart:55:46)
I/flutter ( 5208): │ #1   <asynchronous suspension>
I/flutter ( 5208): │ #2   CommandService.processCommand (package:flutter_jvx/src/service/command/impl/command_service.dart:180:18)
I/flutter ( 5208): │ #3   <asynchronous suspension>
I/flutter ( 5208): │ #4   CommandService._sendCommand (package:flutter_jvx/src/service/command/impl/command_service.dart:129:7)
I/flutter ( 5208): │ #5   <asynchronous suspension>
I/flutter ( 5208): │ #6   _QueuedFuture.execute (package:queue/src/dart_queue_base.dart:26:16)
I/flutter ( 5208): │ #7   <asynchronous suspension>
I/flutter ( 5208): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 5208): │ 16:00:32.582 (+2:55:32.731761)
I/flutter ( 5208): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 5208): │ ⛔ GENERAL: Failed to send startup
I/flutter ( 5208): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


```

**Comment by rjahn** [comment]
This problem is not reproducable. It's only sometimes...

**Comment by rjahn** [comment]
Not reproducable.
